### ISSUE TITLE
smarter taxon image positioning

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#42]
In some cases the taxon image box is too close to the blue taxon node, and may even partly cover it. This depends on the shape of the box and its position relative to the taxon node. We need to make the positioning algorithm a little smarter, i.e., make the taxonImage arrow longer when necessary in order to keep the image box from overlapping other nodes.

**Comment by deyaliao** [comment]
I've fixed this and pushed to the Devel branch, in the file demo2d.html. The vast majority of arrows that point to the taxon image box don't cover any other nodes (some images are just ridiculously big, and I didn't want to make all of the arrows extraordinarily long, unless you think that's a good idea).
<img width="384" alt="Screen Shot 2022-06-26 at 12 09 54 AM" src="https://user-images.githubusercontent.com/61635230/175803523-b8ed2064-6ee8-4bc3-ba58-d2b0ebd9e744.png">

**Comment by touretzkyds** [comment]
The image you posted looks good. But we still have some image placement problems. See below.

![bad-placement](https://user-images.githubusercontent.com/1978092/175804015-9e498e09-729f-404a-b0f0-32aa1fee5b8c.png)

**Comment by deyaliao** [comment]
I made the arrows even longer, but this seems like an issue with calculating the angles of where taxonImage should reside. I could look into that.

**Comment by touretzkyds** [comment]
Yes, just making the arrow longer is not a good solution. We need to consider the placements of the other nodes and then calculate the correct image arrow length to ensure that the image box does not overlap any of the other nodes. I'd like you to do this, but it's a lower priority item right now.
