### ISSUE TITLE
arrows in nav history replaced by boxes

### ISSUE THREAD

**Issue by touretzkyds** [touretzkyds/KnowledgeGraphDemo#53]
In the navigation history display, the left arrow symbol has been replaced by a hollow box.

Not sure what's causing this, but we should not have any special characters in our source files. Use hex or octal character codes to specify special characters.

**Comment by touretzkyds** [comment]
The navigation history arrows aren't showing up as boxes any more, but the old arrows have not been restored. Instead we're getting a skinny double-headed arrow which is not what I wanted. We should be using the same filled triangular arrow as we use for the "left sibling" navigation arrow pointing at "Camelidae" in the image below.

![nav-arrows](https://user-images.githubusercontent.com/1978092/177225623-8a8c34be-2840-407f-8707-dba3b304f8e4.png)

**Comment by nhadlaw** [comment]
Yes sorry that was me just experimenting. I looked into the issue and I think it was just that some symbols aren't supported by certain fonts but I just replaced all symbols with their Unicode equivalent from this wiki source:
https://en.wikipedia.org/wiki/List_of_Unicode_characters
So hopefully that fixed the issue but if not let me know.

**Comment by touretzkyds** [comment]
The arrows are correct now, but their positioning is off. They look like subscripts. They need to be raised up a bit so that the bottom point of the arrow aligns with the baseline of the text.

**Comment by nhadlaw** [comment]
If you look at the current nav buttons I believe this should now be adjusted

**Comment by touretzkyds** [comment]
Looks the same to me:

![arrow-position](https://user-images.githubusercontent.com/1978092/177437020-1c23cd81-ef5c-4057-988f-c597f8ad0fb6.png)

These arrows are too low. They need to be raised up by a few pixels to they don't extend below the baseline.

**Comment by nhadlaw** [comment]
Ok I didn't see it on my end before (i.e. it looked centered) so I don't know if I fixed the issue with the changes that I just pushed but I changed it so the content was centered on the button and hopefully that adjusted it properly. Once again it looks like this on my end:
![image](https://user-images.githubusercontent.com/101290675/177584266-212e9e46-3fab-4892-bcbb-a5989cc6fbfa.png)

So I'm not sure if I fixed it.

**Comment by touretzkyds** [comment]
I'm afraid this is not fixed. Even in  your image you can see the arrows extending below the baseline. Here is what I see in my browser. I positioned things so that there is exactly one pixel of whitespace between the text and the gray line, and I zoomed in to make it very clear what's going on. You can see that the bottom of the arrow is cut off because it extends below the baseline of the text.

![one-pixel](https://user-images.githubusercontent.com/1978092/177589025-d465055a-ced3-4938-8b99-ed8806a61e48.png)

Centering the content on the button won't automatically solve the problem if they are of different font sizes, or if the special character has a different baseline than the letters. One quick and dirty solution for this particular case might be to reduce the font size of the arrow by a tiny bit.

One more thing: you've made a couple of recent posts where your incuded image did not display, such as the posting above. The problem was a space between the "]" and the "(". If you had previewed your post before submitting the comment you would have seen this. I edited the post and fixed it for you, to verify that this was the problem. Be sure to preview your posts if they contain anything fancy like an image upload.
